apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefoods-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubefoods-backend
  template:
    metadata:
      labels:
        app: kubefoods-backend
    spec:
      containers:
        - name: kubefoods-backend
          image: ilopeoso/kubefoods-backend:latest
          ports:
            - containerPort: 3000
